### ISSUE TITLE
ルートディレクトリを変更せずとも動くように

### ISSUE THREAD

**Issue by Nave-wata** [hxs-mini2/Laravel_Forum-B#143]
## 概要

現在はルートディレクトリを変更しなければ動作しない部分がある。それをルートディレクトリの変更なしで動くようにしたい。

## 目的

複数のサービスをディレクトリわけで公開できるようにするため

## タスク

- [ ] ルートディレクトリの変更なしで動かない部分の修正
- [ ] 動作確認

## その他

なし

**Comment by sho037** [comment]
これが実現したらLaravelのプロジェクトをおんなじディレクトリで複数作れるようになるん？

**Comment by Nave-wata** [comment]
出来る様にする予定

**Comment by sho037** [comment]
神

**Comment by Nave-wata** [comment]
- #149 

完了しました
