### ISSUE TITLE
閲覧数や新着順、ほか様々なジャンルで順番に掲示板ページを並べる

### ISSUE THREAD

**Issue by satou1011** [hxs-mini2/Laravel_Forum-B#28]
## 欲しい機能

- 欲しい機能1つにつき，1つのIssueを作成してください
掲示板一つ一つに情報（閲覧数や更新、スレッド作成日時）を付けたしそれらの順番で並べる。
## 目的

- なぜその機能が欲しいのか，それによってどんな良いことがあるのかを記載してください
掲示板の数が増えた際に、多くの人が利用していた有用な掲示板が埋もれないようにしたり、瞬間的にホットな掲示板をよく閲覧されるようにしたい。
## タスク

細かいタスクがある場合はチェックリストにして記載してください
- [ ] 閲覧数順ーその値を比較して、大きい順に並べる
- [ ] 閲覧数順ーアクセスカウンタのカウント基準（複数回のアクセス、リロードなど）を厳密にする
- [ ] 他機能ーー様々な種類の順番を作成し、実装（アクセス数/時間＝＞人気順、リアクションが多い順などアイデア募集）

- [ ] 閲覧数順ーアクセスカウンタを実装する（それぞれの掲示板ごとに）

## その他

- 伝えておくべき事・補足資料などがあれば自由に記載して下さい
他に必要そうなのあったらコメントください。

**Comment by Nave-wata** [comment]
- #120 

完了
