### ISSUE TITLE
スタンプ機能を追加する

### ISSUE THREAD

**Issue by tsuyoshi12345** [hxs-mini2/Laravel_Forum-B#49]
## 欲しい機能

- スタンプ機能を追加する欲しい機能1つにつき，1つのIssueを作成してください

## ラインのスタンプみたいに文字を打たなくても会話を成り立たせれる

- なぜその機能が欲しいのか，それによってどんな良いことがあるのかを記載してください

## タスク

- [ ] 細かいタスクがある場合はチェックリストにして記載してください

## その他

- 伝えておくべき事・補足資料などがあれば自由に記載して下さい

**Comment by Nave-wata** [comment]
掲示板にはいらなさそう&取り組まなさそうなので閉じます
