### ISSUE TITLE
コメントの機能追加

### ISSUE THREAD

**Issue by tsuyoshi12345** [hxs-mini2/Laravel_Forum-B#68]
## 欲しい機能

・Ctrl + enterでコメント送信する

・tabキーでスペースをつけれるようにする

## 目的

わざわざカーソルを移動させず送信できた方が楽だから

## タスク

- [ ] 細かいタスクがある場合はチェックリストにして記載してください

## その他

- 伝えておくべき事・補足資料などがあれば自由に記載して下さい

**Comment by Nave-wata** [comment]
- #161 

で機能追加完了
